version: '3.10'

services:
  app:
    build: .
    stop_signal: SIGKILL
    ports:
      - "5000:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    volumes:
      - ./my_application/main.py:/var/server/app.py
    depends_on:
      - postgres


  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/lib/postgresql/data/pg_log"
    volumes:
      - /tmp/data:/var/lib/postgresql/data

